name: Build
on:
  - push
jobs:
  project:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Node
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: Install
        run: npm install
      - name: Fund
        run: npm fund
      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
