name: Release
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
jobs:
  project:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 20
      - name: Install
        run: npm ci
      - name: Build Release
        run: npm run release
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./public/*.css"
          makeLatest: true
          generateReleaseNotes: true
          draft: true