name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  project:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: Install
        run: npm ci
      - name: Build
        run: npm run release
      - name: Release .css 
        uses: ncipollo/release-action@v1
        with:
          makeLatest: true
          generateReleaseNotes: true
          draft: true
- name: 'Upload DiscordIcons'
    run: |
        cd ${{github.workspace}}
        gh release upload ${{github.event.release.tag_name}} public/DiscordIcons.css        
    env:
      GITHUB_TOKEN: ${{ github.TOKEN }}
    shell: bash